# Generated by Django 5.0.1 on 2024-03-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_donation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.program'),
        ),
    ]
