# Generated by Django 5.0.1 on 2024-03-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_volunteer_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
