# Generated by Django 5.0.1 on 2024-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_vendor',
            new_name='is_volunteer',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='9999999999', max_length=50, null=True),
        ),
    ]
